<?php

/**
 * @file
 * ldnddev Card module file.
 */

/**
 * Implements hook_theme().
 */
function ldnddev_card_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__ldnddev_card' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__ldnddev_card_item' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__ldnddev_card' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__ldnddev_card_item' => [
      'base hook' => 'paragraph',
    ],
  ];
}
